
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjkrrigijnuednkjtgkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqa3JyaWdpam51ZWRua2p0Z2tsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNjE5NzksImV4cCI6MjA1OTczNzk3OX0.MSAndG1zBlWukjYy3Y8tEPEzG8VgAUBqXtwUprs2264";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
